{{- if .Values.podMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "this.fullname" . }}-audit-controller
  labels:
    {{- include "this.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      control-plane: audit-controller
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "this.fullname" . }}-controller-manager
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      control-plane: controller-manager
{{- end }}
